# Expression thresholds
MOUTH_WIDTH_THRESHOLD = 0.07
MOUTH_HEIGHT_THRESHOLD = 0.05
SURPRISE_MOUTH_HEIGHT_THRESHOLD = 13
HAPPY_RATIO_THRESHOLD = 3.0
SURPRISED_RATIO_THRESHOLD = 2.0
SAD_MOUTH_CURVE_THRESHOLD = 0.015
HAPPY_MOUTH_CURVE_THRESHOLD = -0.015
ANGRY_MOUTH_OPEN_THRESHOLD = 0.09
EXPRESSION_BASELINE_FRAMES = 20
EXPRESSION_HAPPY_WIDTH_DELTA = 0.02
EXPRESSION_HAPPY_CURVE_DELTA = 0.012
EXPRESSION_SURPRISE_OPEN_DELTA = 0.03
EXPRESSION_SAD_CURVE_DELTA = 0.012
EXPRESSION_ANGRY_CURVE_DELTA = 0.008
EXPRESSION_ANGRY_WIDTH_DELTA = 0.012

# Head movement thresholds
HEAD_MOVEMENT_X_THRESHOLD = 0.015
HEAD_MOVEMENT_Y_THRESHOLD = 0.02
HEAD_TILT_ANGLE_THRESHOLD = 8.0

# Eye gaze thresholds
GAZE_LEFT_THRESHOLD = 0.4
GAZE_RIGHT_THRESHOLD = 0.6
EYE_CLOSED_RATIO_THRESHOLD = 0.22
EYE_WIDE_RATIO_THRESHOLD = 0.34

# Eyebrow thresholds
EYEBROW_BASELINE_FRAMES = 20
EYEBROW_RAISED_DELTA = 0.012
EYEBROW_FURROWED_DELTA = 0.01
EYEBROW_SPREAD_FURROWED_DELTA = 0.03

# Smoothing window
SMOOTHING_WINDOW = 10
FAST_SMOOTHING_WINDOW = 4

# Overlay controls
SHOW_DEBUG_OVERLAY = False
